# Dockerfile.frontend
FROM python:3.10.0-slim

WORKDIR /app

COPY ../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the contents of the frontend directory into /app/frontend
COPY ../frontend /app/frontend


# Set the working directory to /app/frontend
WORKDIR /app/frontend

CMD ["streamlit", "run", "app.py"]