version: '3.8'

services:
  langchain:
    build:
      context: ./cypherQAchain
      dockerfile: Dockerfile.langchain
    container_name: langchain
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  
  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile.etl
    container_name: etl
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - .:/app
      - ./data:/app/data
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8501:8501"
  
  neo4j:
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data

volumes:
  data: