# src/Dockerfile.langchain
FROM python:3.10.0-slim

# Create and set the working directory
WORKDIR /app

# Copy the requirements.txt from the root directory
COPY ../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the src directory contents to /app
COPY . .

EXPOSE 8001

# Ensure that the uvicorn command points to the correct module and app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
